Updated GitHub CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -127,12 +127,12 @@ jobs:
     - name: Movie Timecode - Build (iOS)
       run: xcodebuild build -project "Examples/Movie Timecode/Movie Timecode.xcodeproj" -scheme "Movie Timecode" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcpretty && exit ${PIPESTATUS[0]}
     
-    - name: TimecodeUI Example - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
+    - name: UI Example - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
       run: xcodebuild -project "Examples/TimecodeUI Example/TimecodeUI Example.xcodeproj" -resolvePackageDependencies | xcpretty && exit ${PIPESTATUS[0]}
-    - name: TimecodeUI Example - Build (macOS)
-      run: xcodebuild build -project "Examples/TimecodeUI Example/TimecodeUI Example.xcodeproj" -scheme "TimecodeUI Example" -destination "generic/platform=macOS,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
-    - name: TimecodeUI Example - Build (iOS)
-      run: xcodebuild build -project "Examples/TimecodeUI Example/TimecodeUI Example.xcodeproj" -scheme "TimecodeUI Example" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcpretty && exit ${PIPESTATUS[0]}
+    - name: UI Example - Build (macOS)
+      run: xcodebuild build -project "Examples/UI Example/UI Example.xcodeproj" -scheme "UI Example" -destination "generic/platform=macOS,name=Any Mac" | xcpretty && exit ${PIPESTATUS[0]}
+    - name: UI Example - Build (iOS)
+      run: xcodebuild build -project "Examples/UI Example/UI Example.xcodeproj" -scheme "UI Example" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcpretty && exit ${PIPESTATUS[0]}
 
 # xcodebuild test reference:
 # https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/08-automation.html
